kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-proxy-ui
  namespace: default
rules:
- apiGroups: 
    - ""
    - "apps"
  resources: 
    - configmaps
    - deployments
    - pods
    - pods/log  
    - secrets
    - services
  verbs:
    - create
    - get
    - list
    - patch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-proxy-ui
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: cloud-proxy-ui
  apiGroup: rbac.authorization.k8s.io
