apiVersion: v1
kind: Service
metadata:
  name: cloud-proxy-ui
spec:
  type: NodePort
  selector:
    app: cloud-proxy-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: ui
      nodePort: 30080
