apiVersion: v1
kind: Service
metadata:
  name: cloud-proxy-ui
spec:
  type: LoadBalancer
  selector:
    app: cloud-proxy-ui
  ports:
    - port: 80
      targetPort: 80
  loadBalancerSourceRanges:
    - 82.172.135.168/32