apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-proxy-ui
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # for AKS this line must be commented out