apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-proxy-ui
spec:
  
  # currently we only support having one replica, so please do NOT change it
  # note the strategy is set to recreate meaning old instance is stopped
  # persistent volume is deattached and new instance is started - this is exactly
  # what we require
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cloud-proxy-ui
  
  template:
    
    metadata:
      name: cloud-proxy-ui
      labels:
        app: cloud-proxy-ui
    
    spec:
      
      containers:

      # nginx container
      - name: nginx
        image: diladele/cloud-proxy-5.1:nginx
        imagePullPolicy: Always
        env:
        - name: DILADELE_WEBSAFETY_HISTORY_DELAY_NOT_USED
          value: "60" # run history every minute for debug now
      
      # ui container
      - name: ui
        image: diladele/cloud-proxy-5.1:ui
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: cloud-proxy-ui-volume
          mountPath: /opt/cloud-proxy/var
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 15

      # logd rsync server container
      - name: logd
        image: diladele/cloud-proxy-5.1:logd
        imagePullPolicy: Always
        ports:
        - containerPort: 873
        env:
        - name: DILADELE_WEBSAFETY_HISTORY_DELAY_NOT_USED
          value: "60" # run history every minute for debug now
        volumeMounts:
        - name: cloud-proxy-ui-volume
          mountPath: /opt/cloud-proxy/var
        readinessProbe:
          tcpSocket:
            port: 873
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 873
          initialDelaySeconds: 15
          periodSeconds: 15

      # realtime container
      - name: realtime
        image: diladele/cloud-proxy-5.1:reports
        imagePullPolicy: Always
        env:
        - name: DILADELE_CLOUDPROXY_REPORTS_REALTIME
          value: "True"
        - name: DILADELE_CLOUDPROXY_REPORTS_DELAY
          value: "15" # runs every 15 seconds        
        volumeMounts:
        - name: cloud-proxy-ui-volume
          mountPath: /opt/cloud-proxy/var

      # history container
      - name: history
        image: diladele/cloud-proxy-5.1:reports
        imagePullPolicy: Always
        env:
        - name: DILADELE_CLOUDPROXY_REPORTS_DELAY
          value: "3600" # runs every 3600 seconds / 1 hour
        volumeMounts:
        - name: cloud-proxy-ui-volume
          mountPath: /opt/cloud-proxy/var

      initContainers:      
      - name: init
        image: diladele/cloud-proxy-5.1:uiinit
        imagePullPolicy: Always
        volumeMounts:
        - name: cloud-proxy-ui-volume
          mountPath: /opt/cloud-proxy/var
        
      volumes:
        - name: cloud-proxy-ui-volume
          persistentVolumeClaim:
            claimName: cloud-proxy-ui
