apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-proxy.fullname" . }}
  labels:
    {{- include "cloud-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloud-proxy.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.restrictSourceRanges }}
  loadBalancerSourceRanges:
    {{- .Values.service.sourceRanges | toYaml | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-proxy.fullname" . }}-reports
  labels:
    {{- include "cloud-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 873
      targetPort: 873
      protocol: TCP
  selector:
    {{- include "cloud-proxy.selectorLabels" . | nindent 4 }}